[sdl]
fullscreen=false
windowresolution=1024x768
autolock=false

[mouse]
mouse_type=ps2
middle_lock=false
mouse_sensitivity=20

[dosbox]
machine=svga_s3
memsize=16

[render]
scaler=none

[cpu]
core=dynamic
cputype=pentium_slow
cycles=max

[autoexec]
mount c .
c:
cd tp7\bin
set PATH=C:\TP7\BIN
cd \
build.bat