# Config Settings File

InsetColors=7
BKColor=0
TBColor=27
WinColor=7
BTNFace=7
BTNFont=17
DarkShad=8
LightShad=15
FontColor=15
MenuOn=7
MenuOff=7
WallPaper=pge.pcx
Res=1

#Resolutions are
# 1: 640x480
# 2: 800x600
# 3: 1024x768
# 4: 1280x1024


# Dark Colors:
#(Foreground & Background)
# ออออออออออออออออออออออออ
# Black         0
# Blue          1
# Green         2
# Cyan          3
# Red           4
# Magenta       5
# Brown         6
# LightGray     7
#
# Light Colors:
#(Foreground)
# อออออออออออออออออ
# DarkGray       8
# LightBlue      9
# LightGreen    10
# LightCyan     11
# LightRed      12
# LightMagenta  13
# Yellow        14
# White         15

